import "./src/css/main.css"
import "./src/css/navbar.css"
import "./src/css/contact.css"
import "./src/css/footer.css"
import "./src/css/scroll-top.css"
import "./src/css/form-submitted.css"
import "./src/css/sliders.css"
import "./src/css/stripper-template.css"